# Generated by Django 5.0.1 on 2024-02-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMarks',
            new_name='SubjectMarks',
        ),
    ]
